language: node_js
node_js:
    - stable
addons:
    browserstack:
      username: dashJSUserName
      access_key:
          secure: dashJSEncryptedAccessKey
before_install: npm install -g grunt-cli
after_success:
  - test $TRAVIS_BRANCH = "development" && grunt deploy --ftp-host=$DEPLOY_HOST --ftp-user=$DEPLOY_USER --ftp-pass=$DEPLOY_PASSWORD
install:
    - npm install
script:
    # Build the source files
    - npm run build
     # If job triggered by cron job, then run tests
    - if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then npm run test_functional ; fi