version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run buld and tests!
      # - run:
      #    name: Build and Test
      #    command: npm run build

    machine:
      ruby:
        version: 2.0.0-p0
      environment:
        BS_USERNAME: $BS_USERNAME
        BS_AUTHKEY: $BS_AUTHKEY
        SELENIUM_HOST: hub.browserstack.com
        BS_AUTOMATE_PROJECT: "Run on circleCI"
        BS_AUTOMATE_BUILD: "build No. $CIRCLE_BUILD_NUM for circleCI"
        SELENIUM_PLATFORM: WINDOWS
        BS_AUTOMATE_OS_VERSION: 10
        SELENIUM_BROWSER: CHROME
        SELENIUM_VERSION: 11

      - run:
          name: Run functional tests
          command: npm run test-functional -- browser=chrome stream="VOD (Static MPD)"
        environment:

      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "development" ]; then
              sudo npm install -g grunt-cli
              grunt deploy --git-commit=$CIRCLE_SHA1 --ftp-host=$DEPLOY_HOST --ftp-user=$DEPLOY_USER --ftp-pass=$DEPLOY_PASSWORD
            else
              echo "Not development branch, dry run only"
            fi

